services:
    uam_aws_ecs.aws:
        class: Guzzle\Service\Builder\ServiceBuilder
        factory_class: UAM\Aws\Ecs\Aws
        factory_method: factory
        arguments:
            - %uam_aws_ecs%
